sudo: no
dist: trusty

language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pyyaml
# command to run tests
script:
  - coverage run --source='.' manage.py test
  - coverage report
after_success:
  - coveralls
